// src/routes/+page.svelte
<script lang="ts">
	import '../app.css';
	import LinkOut from '$lib/assets/link-out.svg?component';
	import AddPeople from '$lib/assets/add-people.svg?component';
	import PlayerEntry from './playerEntry.svelte';
	import { savedStore } from '$lib/savedStore';
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { enhance, type SubmitFunction } from '$app/forms';
	import type { PageData } from './$types';

	let usernames = savedStore('usernames', '');
	let exact = savedStore('exact', true);

	export let data: PageData;

	$: if (data.usernames) $usernames = data.usernames;
	$: if (!data.exact) $exact = data.exact;

	onMount(() => {
		const params = new URLSearchParams(window.location.search);
		if (
			($usernames && params.get('usernames') !== $usernames) ||
			(!$exact && params.get('exact') !== String($exact))
		) {
			search();
		}
	});

	const search = () => {
		const params = new URLSearchParams({
			...($usernames && { usernames: $usernames }),
			...(!$exact && { exact: String($exact) })
		}).toString();

		goto(params ? `/?${params}` : '/', { keepfocus: true });
	};

	const onSubmit: SubmitFunction = ({ cancel }) => {
		cancel();
		search();
	};

	const onExactChange = (event: Event) => {
		$exact = (event.target as HTMLInputElement).checked;
		search();
	};

	$: title = `Rankings for ${
		data.leaderboard && data.leaderboard.players.length > 0
			? data.leaderboard.players.map((player) => player.username).join(', ')
			: data.usernames
	}`;
</script>

<svelte:head>
	{#if data.leaderboard}
		<title>{title}</title>
		<meta property="og:title" content={title} />
		<meta
			property="og:description"
			content={data.leaderboard.players
				.map(
					(player) =>
						`${player.rank + 1}. ${player.username} (${player.points} Points${
							player.winStreak > 0 ? `, ${player.winStreak} W` : ''
						})`
				)
				.concat([`Games: ${data.leaderboard.games}`])
				.join('\n')}
		/>
	{/if}
</svelte:head>

<nav>
	<div class="nav-center">
		<a class="nav-link" href="https://colonist.io/" target="_blank">
			<p>Colonist</p>
			<LinkOut alt="External link icon" />
		</a>
		<p class="games-text">
			{#if data.leaderboard}
				Games played: {data.leaderboard.games}
			{/if}
		</p>
	</div>
</nav>

<main>
	<h1 class="logo">Colonist Leaderboard</h1>

	<form class="form-wrapper" use:enhance={onSubmit} method="post">
		<div class="input">
			<input
				type="text"
				placeholder="Enter a comma-separated list of players..."
				bind:value={$usernames}
				name="usernames"
			/>
			<button>
				<AddPeople alt="Add people icon" />
			</button>
		</div>
		<label class="checkbox-label">
			Exact Match
			<input type="checkbox" checked={$exact} name="exact" on:change={onExactChange} />
		</label>
	</form>

	{#if data.leaderboard}
		{#each data.leaderboard.players as player}
			<PlayerEntry {player} />
		{:else}
			<h2>No games</h2>
		{/each}
	{/if}
</main>

<style>
	/* NAV SECTION */

	nav {
		font-size: 14px;
		width: 100%;
		height: 42px;
		background-color: var(--surface);
	}

	.nav-center {
		max-width: 900px;
		height: 42px;
		width: 100%;
		margin: auto;
		display: flex;
		flex-direction: row;
		justify-content: space-between;
		align-items: center;
		text-align: center;
	}

	.nav-link {
		height: 100%;
		padding: 0 6px 0 10px;
		display: flex;
		flex-direction: row;
		align-items: center;
		gap: 6px;
		text-decoration: none;
		cursor: pointer;
		color: var(--light-font);
		background-color: transparent;
		transition: box-shadow 0.2s, color 0.2s, background-color 0.2s;
	}

	.nav-link:focus-visible {
		outline: none;
		color: var(--blue-font);
		background-color: var(--blue-background);
	}

	.nav-link:focus-visible :global(svg path) {
		fill: var(--blue-font);
	}

	.nav-link:hover {
		color: var(--font);
		background-color: var(--nav-hover);
	}

	.nav-link :global(svg path) {
		fill: var(--light-font);
		transition: fill 0.2s;
	}

	.nav-link :global(svg) {
		height: 20px;
	}

	.nav-link:hover :global(svg path) {
		fill: var(--font);
	}

	.games-text {
		color: var(--light-font);
		padding-right: 10px;
	}

	/* MAIN SECTION */

	h2 {
		display: flex;
		justify-content: center;
	}

	main {
		max-width: 900px;
		padding: 0 10px;
		margin: auto;
	}

	.logo {
		font-size: 20px;
		color: var(--blue-font);
		padding: 24px 0 20px 0;
		display: flex;
		justify-content: center;
	}

	.form-wrapper {
		display: flex;
		flex-direction: row;
		justify-content: center;
		align-items: center;
		margin-bottom: 24px;
		gap: 12px;
	}

	.checkbox-label {
		height: 50px;
		padding: 0 18px;
		border-radius: 500px;
		cursor: pointer;
		display: flex;
		flex-direction: column-reverse;
		justify-content: center;
		align-items: center;
		gap: 4px;
		font-size: 12px;
		white-space: nowrap;
		color: var(--light-font);
		background-color: var(--surface);
		box-shadow: rgba(0, 0, 0, 0.1) 0px 2px 8px 0px;
		transition: background-color 0.2s;
	}

	[type='checkbox']:focus-visible {
		outline: 2px solid var(--blue-font);
	}

	.checkbox-label:hover {
		background-color: var(--surface-hover);
	}

	/* CHECKBOX */

	[type='checkbox'] {
		width: 16px;
		height: 16px;
		color: var(--blue-font);
		vertical-align: middle;
		-webkit-appearance: none;
		background: none;
		border: 0;
		outline: 0;
		flex-grow: 0;
		border-radius: 50%;
		background-color: var(--background);
		transition: background-color 0.2s;
		cursor: pointer;
	}

	/* Pseudo element for check styling */

	[type='checkbox']::before {
		content: '';
		color: transparent;
		display: block;
		width: inherit;
		height: inherit;
		border-radius: inherit;
		border: 0;
		background-color: transparent;
		background-size: contain;
		box-shadow: inset 0 0 0 1px var(--nav-hover);
	}

	/* Checked */

	[type='checkbox']:checked {
		background-color: var(--checkbox-background);
	}

	[type='checkbox']:checked::before {
		box-shadow: none;
		background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24'%3E %3Cpath d='M15.88 8.29L10 14.17l-1.88-1.88a.996.996 0 1 0-1.41 1.41l2.59 2.59c.39.39 1.02.39 1.41 0L17.3 9.7a.996.996 0 0 0 0-1.41c-.39-.39-1.03-.39-1.42 0z' fill='%23fff'/%3E %3C/svg%3E");
	}

	.input {
		flex: 1;
		display: flex;
		max-width: 500px;
		min-width: 0;
		height: 50px;
		background-color: var(--surface);
		border-radius: 500px;
		box-shadow: rgba(0, 0, 0, 0.1) 0px 2px 8px 0px;
	}

	.input input {
		min-width: 0;
		font-size: 16px;
		padding: 0 22px;
		background-color: transparent;
		border: 2px solid transparent;
		border-radius: 500px 0 0 500px;
		flex: 1;
		transition: background-color 0.2s;
	}

	.input input:hover {
		background-color: var(--surface-hover);
	}

	.input input:focus {
		outline: none;
		border: 2px solid var(--blue-font);
		background-color: var(--surface-hover);
	}

	.input input::placeholder {
		color: var(--light-font);
	}

	.input button {
		cursor: pointer;
		background-color: var(--blue-font);
		height: 50px;
		width: 50px;
		border: none;
		padding: 4px;
		border-radius: 0 500px 500px 0;
		transition: background-color 0.2s;
	}

	.input button:focus-visible {
		background-color: var(--font);
	}

	.input button:hover {
		background-color: var(--button-hover);
	}

	.input button :global(svg) {
		margin-right: 3px;
	}

	.input button :global(svg path) {
		fill: var(--button);
	}

	@media only screen and (max-width: 768px) {
		.logo {
			font-size: 16px;
		}
	}
</style>

// src/routes/index.tsx
import {
	createAsync,
	useSearchParams,
	useNavigate,
	type RoutePreloadFuncArgs
} from '@solidjs/router';
import { Title, Meta } from '@solidjs/meta';
import { For, Show, onMount, createMemo, createSignal, batch } from 'solid-js';
import ConfirmDialog from '~/components/ConfirmDialog';
import { getLeaderboard } from '~/lib/api';
import { formatDuration } from '~/lib/format';
import { createLocalSignal } from '~/lib/createLocalSignal';
import PlayerEntry from '~/components/PlayerEntry';
import MatchHistory from '~/components/MatchHistory';
import Overview from '~/components/Overview';
import linkOutSvg from '~/lib/assets/link-out.svg?raw';
import addPeopleSvg from '~/lib/assets/add-people.svg?raw';

interface Bookmark {
	name: string;
	usernames: string;
	exact: boolean;
}

export const route = {
	preload({ location }: RoutePreloadFuncArgs) {
		const params = new URLSearchParams(location.search);
		getLeaderboard(
			params.get('usernames') ?? '',
			(params.get('exact') ?? 'true') === 'true',
			params.get('limit') ?? ''
		);
	}
};

export default function Home() {
	const [searchParams] = useSearchParams();
	const navigate = useNavigate();
	const [usernames, setUsernames] = createLocalSignal('usernames', '');
	const [exact, setExact] = createLocalSignal('exact', true);
	const [bookmarks, setBookmarks] = createLocalSignal<Bookmark[]>('bookmarks', []);
	const [bookmarkName, setBookmarkName] = createSignal('');
	const [showBookmarkInput, setShowBookmarkInput] = createSignal(false);
	const [deletingBookmark, setDeletingBookmark] = createSignal<string | null>(null);
	const [hoveredPlayer, setHoveredPlayer] = createSignal<string | null>(null);
	const [activeTab, setActiveTab] = createSignal<'details' | 'overview'>('details');

	const leaderboard = createAsync(() =>
		getLeaderboard(
			(searchParams.usernames as string) ?? '',
			(searchParams.exact ?? 'true') === 'true',
			(searchParams.limit as string) ?? ''
		)
	);

	createMemo(() => {
		if (searchParams.usernames) setUsernames(searchParams.usernames as string);
	});
	createMemo(() => {
		if (searchParams.exact !== undefined) setExact(searchParams.exact === 'true');
	});

	onMount(() => {
		if (
			(usernames() && searchParams.usernames !== usernames()) ||
			(!exact() && searchParams.exact !== String(exact()))
		) {
			search();
		}
	});

	const search = () => {
		const params = new URLSearchParams({
			...(usernames() && { usernames: usernames() }),
			...(!exact() && { exact: String(exact()) })
		}).toString();

		navigate(params ? `/?${params}` : '/', { resolve: false });
	};

	const onSubmit = (e: SubmitEvent) => {
		e.preventDefault();
		search();
	};

	const onExactChange = (e: Event) => {
		setExact((e.target as HTMLInputElement).checked);
		search();
	};

	const saveBookmark = () => {
		const name = bookmarkName().trim();
		const currentUsernames = usernames().trim();
		if (!name || !currentUsernames) return;
		setBookmarks((prev) => [
			...prev.filter((b) => b.name !== name),
			{ name, usernames: currentUsernames, exact: exact() }
		]);
		setBookmarkName('');
		setShowBookmarkInput(false);
	};

	const loadBookmark = (bookmark: Bookmark) => {
		setUsernames(bookmark.usernames);
		setExact(bookmark.exact);
		search();
	};

	const deleteBookmark = (name: string) => {
		setDeletingBookmark(name);
	};

	const confirmDelete = () => {
		const name = deletingBookmark();
		if (!name) return;
		batch(() => {
			setBookmarks((prev) => prev.filter((b) => b.name !== name));
			setDeletingBookmark(null);
		});
	};

	const title = createMemo(() => {
		const lb = leaderboard();
		return `Rankings for ${
			lb && lb.players.length > 0
				? lb.players.map((p) => p.username).join(', ')
				: searchParams.usernames ?? ''
		}`;
	});

	const ogDescription = createMemo(() => {
		const lb = leaderboard();
		if (!lb) return '';
		return lb.players
			.map(
				(player) =>
					`${player.rank + 1}. ${player.username} (${player.points} Points${
						player.winStreak > 0 ? `, ${player.winStreak} W` : ''
					})`
			)
			.concat([`Games: ${lb.games}`])
			.join('\n');
	});

	return (
		<>
			<Show when={leaderboard()}>
				<Title>{title()}</Title>
				<Meta property="og:title" content={title()} />
				<Meta property="og:description" content={ogDescription()} />
			</Show>

			<nav>
				<div class="nav-center">
					<a class="nav-link" href="https://colonist.io/" target="_blank">
						<p>Colonist</p>
						<span innerHTML={linkOutSvg} />
					</a>

					<form class="nav-search" onSubmit={onSubmit}>
						<div class="input">
							<input
								type="text"
								placeholder="Enter players..."
								value={usernames()}
								onInput={(e) => setUsernames(e.currentTarget.value)}
								name="usernames"
							/>
							<button type="submit">
								<span innerHTML={addPeopleSvg} />
							</button>
						</div>
						<label class="checkbox-label">
							Exact
							<input type="checkbox" checked={exact()} name="exact" onChange={onExactChange} />
						</label>
						<button
							type="button"
							class="bookmark-btn"
							title="Bookmark current players"
							onClick={() => setShowBookmarkInput((v) => !v)}
						>
							<svg width="18" height="18" viewBox="0 0 24 24" fill="none">
								<path
									d="M6 2C5.44772 2 5 2.44772 5 3V21C5 21.3746 5.21608 21.7178 5.55279 21.8944C5.88951 22.0711 6.29443 22.0517 6.6139 21.8444L12 18.2229L17.3861 21.8444C17.7056 22.0517 18.1105 22.0711 18.4472 21.8944C18.7839 21.7178 19 21.3746 19 21V3C19 2.44772 18.5523 2 18 2H6Z"
									fill="currentColor"
								/>
							</svg>
						</button>
					</form>
				</div>
			</nav>

			<Show when={showBookmarkInput()}>
				<div class="bookmark-save-row">
					<input
						type="text"
						class="bookmark-name-input"
						placeholder="Bookmark name..."
						value={bookmarkName()}
						onInput={(e) => setBookmarkName(e.currentTarget.value)}
						onKeyDown={(e) => e.key === 'Enter' && saveBookmark()}
					/>
					<button class="bookmark-save-btn" onClick={saveBookmark}>
						Save
					</button>
				</div>
			</Show>

			<Show when={bookmarks().length > 0}>
				<div class="bookmarks-list">
					<For each={bookmarks()}>
						{(bookmark) => (
							<div class="bookmark-chip">
								<button class="bookmark-load" onClick={() => loadBookmark(bookmark)}>
									{bookmark.name}
								</button>
								<button
									class="bookmark-delete"
									onClick={() => deleteBookmark(bookmark.name)}
								>
									&times;
								</button>
							</div>
						)}
					</For>
				</div>
			</Show>

			<Show when={leaderboard()}>
				{(lb) => (
					<>
						<div class="stats-bar">
							<p>Games played: {lb().games}</p>
							{lb().avgDuration > 0 && (
								<p>Avg Duration: {formatDuration(lb().avgDuration)}</p>
							)}
						</div>

						<main>
							<Show when={lb().players.length > 0} fallback={<h2>No games</h2>}>
								<div class="tabs">
									<button
										class="tab"
										classList={{ 'tab-active': activeTab() === 'details' }}
										onClick={() => setActiveTab('details')}
									>
										Match Details
									</button>
									<button
										class="tab"
										classList={{ 'tab-active': activeTab() === 'overview' }}
										onClick={() => setActiveTab('overview')}
									>
										Overview
									</button>
								</div>

								<Show when={activeTab() === 'details'}>
									<div class="content-layout">
										<div class="rankings-col">
											<For each={lb().players}>
												{(player) => (
													<PlayerEntry
														player={player}
														onHover={setHoveredPlayer}
													/>
												)}
											</For>
										</div>
										<div class="history-col">
											<MatchHistory
												games={lb().matchHistory}
												hoveredPlayer={hoveredPlayer()}
											/>
										</div>
									</div>
								</Show>

								<Show when={activeTab() === 'overview'}>
									<Overview leaderboard={lb()} />
								</Show>
							</Show>
						</main>
					</>
				)}
			</Show>

			<ConfirmDialog
				message={`Delete bookmark "${deletingBookmark()}"?`}
				open={deletingBookmark() !== null}
				onConfirm={confirmDelete}
				onCancel={() => setDeletingBookmark(null)}
			/>
		</>
	);
}
