// src/routes/playerEntry.svelte
<script lang="ts">
	import Gold from '$lib/assets/gold.svg?component';
	import Silver from '$lib/assets/silver.svg?component';
	import Bronze from '$lib/assets/bronze.svg?component';
	import type { Player } from './+page.server';

	export let player: Player;
</script>

<a class="player-wrapper" href="https://colonist.io/profile/{player.username}" target="_blank">
	<div class="row gap m-column center">
		<div class="row gap center">
			<h2 class:first={player.rank === 0}>{player.rank + 1}</h2>
			<div class="player name">
				<h3>{player.username}</h3>
				<p>{player.points} Points</p>
			</div>
		</div>
		<div class="row gap center">
			<div class="player center">
				<h4>Streak</h4>
				<div>
					<p class={player.winStreak >= player.lossStreak ? 'win chip' : 'loss chip'}>
						{player.winStreak >= player.lossStreak
							? `${player.winStreak} W`
							: `${player.lossStreak} L`}
					</p>
				</div>
			</div>
			<div class="player center">
				<h4>Longest Streak</h4>
				<div>
					<p class="chip">{player.longestWinStreak} W</p>
					<p class="chip">{player.longestLossStreak} L</p>
				</div>
			</div>
			<div class="player center">
				<h4>Win %</h4>
				<p class="chip clear">{Math.round(player.winPercent * 100)}%</p>
			</div>
		</div>
	</div>

	<div class="row medal-wrapper center">
		<div class="row medals center">
			<Gold alt="Gold medal icon" />
			<p>{player.ranks[0]}</p>
		</div>
		<div class="row medals center">
			<Silver alt="Silver medal icon" />
			<p>{player.ranks[1]}</p>
		</div>
		<div class="row medals center">
			<Bronze alt="Bronze medal icon" />
			<p>{player.ranks[2]}</p>
		</div>
	</div>
</a>

<style>
	.player-wrapper {
		color: var(--font);
		text-decoration: none;
		box-sizing: border-box;
		background-color: var(--surface);
		border-radius: 12px;
		padding: 8px 18px;
		margin-bottom: 16px;
		display: flex;
		flex-direction: row;
		justify-content: space-between;
		align-items: center;
		transition: background-color 0.2s;
	}

	.player-wrapper:focus-visible {
		outline: 2px solid var(--blue-font);
	}

	.player-wrapper:hover {
		background-color: var(--surface-hover);
	}

	h2 {
		font-size: 24px;
		padding: 15px;
		border-radius: 12px;
		color: var(--blue-font);
		background-color: var(--blue-background);
	}

	.first {
		color: var(--gold-font);
		background-color: var(--gold-background);
	}

	.row {
		display: flex;
		flex-direction: row;
	}

	.gap {
		gap: 32px;
	}

	.name {
		width: 100px;
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
	}

	.player {
		display: flex;
		flex-direction: column;
		gap: 6px;
	}

	.center {
		align-items: center;
	}

	.player h3 {
		font-size: 18px;
		color: var(--font);
	}

	.player h4 {
		font-size: 14px;
		opacity: 0.4;
		color: var(--font);
	}

	.player p {
		font-size: 14px;
		color: var(--light-font);
	}

	.medal-wrapper {
		gap: 6px;
	}

	.medals {
		justify-content: center;
		background-color: var(--background);
		padding: 6px 10px 6px 6px;
		min-width: 60px;
		border-radius: 8px;
		gap: 4px;
	}

	.medals :global(svg) {
		height: 24px;
	}

	p.chip {
		display: inline-block;
		padding: 4px 6px;
		border-radius: 4px;
		color: var(--light-font);
		background-color: var(--nav-hover);
		min-width: 24px;
		text-align: center;
	}

	p.clear {
		background-color: transparent;
	}

	p.win {
		color: var(--green-font);
		background-color: var(--green-background);
	}

	p.loss {
		color: var(--red-font);
		background-color: var(--red-background);
	}

	@media only screen and (max-width: 768px) {
		.player-wrapper {
			flex-direction: column;
			gap: 16px;
		}

		.gap {
			gap: 16px;
		}
	}

	@media only screen and (max-width: 500px) {
		.m-column {
			flex-direction: column;
		}
	}
</style>

// src/components/PlayerEntry.tsx
import { createSignal, For, Show } from "solid-js";
import bronzeSvg from "~/lib/assets/bronze.svg?raw";
import goldSvg from "~/lib/assets/gold.svg?raw";
import silverSvg from "~/lib/assets/silver.svg?raw";
import { formatDuration } from "~/lib/format";
import type { Player } from "~/lib/types";

function formatDate(ms: number): string {
    const d = new Date(ms);
    return d.toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" });
}

function ordinal(rank: number): string {
    if (rank === 1) return "1st";
    if (rank === 2) return "2nd";
    if (rank === 3) return "3rd";
    return `${rank}th`;
}

export default function PlayerEntry(props: {
    player: Player;
    onHover: (username: string | null) => void;
    hideGames?: boolean;
}) {
    const [expanded, setExpanded] = createSignal(false);

    const toggle = (e: MouseEvent) => {
        e.preventDefault();
        setExpanded((v) => !v);
    };

    const sortedGames = () => [...props.player.games].reverse();

    return (
        <div
            class="player-card"
            onMouseEnter={() => props.onHover(props.player.username)}
            onMouseLeave={() => props.onHover(null)}
        >
            <a
                class="player-wrapper"
                href={`https://colonist.io/profile/${props.player.username}`}
                target="_blank"
            >
                <div class="row gap m-column center">
                    <div class="row gap center">
                        <h2 class={{ first: props.player.rank === 0 }}>{props.player.rank + 1}</h2>
                        <div class="player name">
                            <h3>{props.player.username}</h3>
                            <p>{props.player.points} Points</p>
                        </div>
                    </div>
                    <div class="row gap center">
                        <div class="player center">
                            <h4>Streak</h4>
                            <div>
                                <p
                                    class={
                                        props.player.winStreak >= props.player.lossStreak
                                            ? "win chip"
                                            : "loss chip"
                                    }
                                >
                                    {props.player.winStreak >= props.player.lossStreak
                                        ? `${props.player.winStreak} W`
                                        : `${props.player.lossStreak} L`}
                                </p>
                            </div>
                        </div>
                        <div class="player center">
                            <h4>Longest Streak</h4>
                            <div>
                                <p class="chip">{props.player.longestWinStreak} W</p>
                                <p class="chip">{props.player.longestLossStreak} L</p>
                            </div>
                        </div>
                        <div class="player center">
                            <h4>Win %</h4>
                            <p class="chip clear">{Math.round(props.player.winPercent * 100)}%</p>
                        </div>
                    </div>
                </div>

                <div class="row medal-wrapper center">
                    <div class="row medals center">
                        <span innerHTML={goldSvg} />
                        <p>{props.player.ranks[0]}</p>
                    </div>
                    <div class="row medals center">
                        <span innerHTML={silverSvg} />
                        <p>{props.player.ranks[1]}</p>
                    </div>
                    <div class="row medals center">
                        <span innerHTML={bronzeSvg} />
                        <p>{props.player.ranks[2]}</p>
                    </div>
                </div>
            </a>

            <Show when={!props.hideGames}>
                <button class="expand-btn" onClick={toggle}>
                    <svg
                        class={["expand-icon", { "expand-icon-open": expanded() }]}
                        width="16"
                        height="16"
                        viewBox="0 0 24 24"
                        fill="none"
                    >
                        <path
                            d="M7 10l5 5 5-5"
                            stroke="currentColor"
                            stroke-width="2"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                        />
                    </svg>
                    {expanded() ? "Hide" : "Show"} Games ({props.player.gamesPlayed})
                </button>

                <Show when={expanded()}>
                    <div class="games-list">
                        <div class="game-row game-header">
                            <span class="game-col game-date">Date</span>
                            <span class="game-col game-place">Place</span>
                            <span class="game-col game-vp">VP</span>
                            <span class="game-col game-turns">Turns</span>
                            <span class="game-col game-dur">Duration</span>
                            <span class="game-col game-players">Players</span>
                        </div>
                        <For each={sortedGames()}>
                            {(game) => (
                                <div class={["game-row", { "game-win": game().rank === 1 }]}>
                                    <span class="game-col game-date">
                                        {formatDate(game().date)}
                                    </span>
                                    <span class="game-col game-place">
                                        <span
                                            class={{
                                                "win chip": game().rank === 1,
                                                "loss chip": game().rank !== 1,
                                            }}
                                        >
                                            {ordinal(game().rank)}
                                        </span>
                                    </span>
                                    <span class="game-col game-vp">{game().vp}</span>
                                    <span class="game-col game-turns">{game().turnCount}</span>
                                    <span class="game-col game-dur">
                                        {formatDuration(game().duration)}
                                    </span>
                                    <span class="game-col game-players">
                                        {game()
                                            .players.sort((a, b) => a.rank - b.rank)
                                            .map((p) => p.username)
                                            .join(", ")}
                                    </span>
                                </div>
                            )}
                        </For>
                    </div>
                </Show>
            </Show>
        </div>
    );
}
